# see: https://goreleaser.com/customization/

project_name: snake

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: ./mian.go
    binary: snake
    ldflags: -s -w -X main.Version={{.Version}}  -X main.BuildDate={{.Date}} -X main.commit={{.Commit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

archives:
  - id: snake
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

release:
  github:
    owner: qloog
    name: snake
  name_template: '{{.Tag}}'