{
 "title": "Go Metrics for testing",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(go_goroutines, namespace)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$namespace\",service=\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "请求耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(eagle_http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "all_request_duration_seconds_bucket | 1m"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(eagle_http_request_duration_seconds_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m]))by (service, handler, instance, le))",
     "legendFormat": "{{service}} | {{instance}} | url=\"{{handler}}\"  "
    }
   ]
  },
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eagle_http_requests_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}} | {{instance}} | url=\"{{handler}}\"  "
    },
    {
     "expr": "sum(rate(eagle_http_requests_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m])) by (service, handler)",
     "legendFormat": " {{service}} | url=\"{{handler}}\" "
    }
   ]
  },
  {
   "title": "POD-CPU 平均使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m]) * 100)/count(process_cpu_seconds_total{namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "CPU平均使用率"
    },
    {
     "expr": "count(process_cpu_seconds_total{namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "pod数量"
    }
   ]
  },
  {
   "title": "Request Size [+Inf]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum  by (service, instance, handler, le) (rate(eagle_http_request_size_bytes_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\", le=\"+Inf\"}[5m]))",
     "legendFormat": "{{service}} | {{instance}} | \"{{handler}}\" | le={{le}}  | 5m"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m]) * 100",
     "legendFormat": "process_cpu_usage_1m | {{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "Response Size [95]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(eagle_http_request_size_bytes_bucket{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[5m])) by (service, handler, le))",
     "legendFormat": "{{service}} | {{instance}} | \"{{handler}}\"  | 5m"
    }
   ]
  },
  { "title": "Go Internal Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Open File Handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{service}} | {{instance}} | pod={{pod}} | quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "{{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_gc_sys_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"} - go_memstats_other_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_next_gc_bytes | {{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_sys_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_idle_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_released_bytes | {{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"} - go_memstats_frees_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "number_of_live_objects | {{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m])",
     "legendFormat": "go_memstats_mallocs | {{service}} | {{instance}} | pod={{pod}} | 1m"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes | {{service}} | {{instance}} | pod={{pod}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_sys_bytes | {{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m])",
     "legendFormat": "go_memstats_alloc_bytes | {{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{namespace=\"$namespace\", service=\"$service\", pod=~\"$pod\"}[1m])",
     "legendFormat": "go_memstats_lookups | {{service}} | {{instance}} | pod={{pod}}"
    }
   ]
  }
 ]
}